### ISSUE TITLE
Add current research statement

### ISSUE THREAD

**Issue by caseyg** [caseyg/melchua#10]
Hey Mel, I added some text from your old site to the Research Statement page. But were you planning to re-write or edit it, based on what you had started working on in our Paper docs?

https://github.com/caseyg/melchua/blob/gh-pages/research-statement.md

https://paper.dropbox.com/doc/Written-exercises-lI1XGblIGtPRYVgme9uB7

Feel free to keep as is or edit right in the markdown file, and/close this issue when you've had a chance to take a look over it.

**Comment by mchua** [comment]
I've edited it to be more updated - a research statement is something I'll need to think about and revise pretty deeply for job applications this summer/fall, but this is a good proxy for length and style, and not totally off base in terms of content.
