### ISSUE TITLE
Edit CV page down

### ISSUE THREAD

**Issue by caseyg** [caseyg/melchua#2]

**Comment by caseyg** [comment]
@mchua I converted the Word Doc CV you sent me to a Markdown file 👍, but I had previously found an earlier version of a CV on your previous website (starting at line 246 in the same file). If that old info is irrelevant want to go ahead and just delete everything from that point down? Or edit in whatever you'd like to keep, then feel free to close this issue.

https://github.com/caseyg/melchua/blame/gh-pages/cv.md#L246

**Comment by mchua** [comment]
Yep, deleted everything from that point down. Yay!

One note here - not sure if I want to have my full address/email/phone on the final website version of the CV, so I've taken that out too.
